version: '3.8'

services:
  llm-chat-app:
    build: .
    container_name: llm-chat-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8501:8501"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
networks:
  default:
    name: llm-chat-network